exports.NAME_LENGTH = '"displayName" length must be at least 8 characters long';
exports.EMAIL_FIELD = '"email" is required';
exports.EMAIL_EMPTY = '"email" is not allowed to be empty';
exports.EMAIL_REGEX = '"email" must be a valid email';
exports.PASSWORD_FIELD = '"password" is required';
exports.PASSWORD_EMPTY = '"password" is not allowed to be empty';
exports.PASSWORD_SIZE = '"password" length must be 6 characters long';
exports.TITLE_FIELD = '"title" is required';
exports.CONTENT_FIELD = '"content" is required';
